namespace TaxCardFormat.Enums;

/// <summary>
/// Dokumentation findes her: https://info.skat.dk/data.aspx?oid=1745573
/// </summary>
public enum Vaerdisaet6001
{
    AIndkomstMedAmBidrag = 0013,
    AIndkomstUdenAmBidrag = 0014,
    IndeholdtASkat = 0015,
    IndeholdtAmBidrag = 0016,
    VeardiAfFriBil = 0019,
    VeardiAfFriTelefon = 0020,
    VeardiAfFriKostOgLogi = 0021,
    IndskudIAndenUdlandskPension = 0022,
    AmBidragAfIndskud = 0023,
    SkattefriUdbetalingAfUdlandskPension = 0025,
    VeardiAfArbejdsgiverUdbetaltSundhedsforsikring = 0026,
    BIndkomstUdenbetaltAmBidrag = 0036,
    OffentligeTilskudTilVirksomhed = 0037,
    BIndkomstUdenPaakrevetAmBidrag = 0038,
    Haedersgaver = 0039,
    BruttoindskudIMedarbejderindvesteringsselskab = 0041,
    AmBidragAfIndskudIMedarbejderindvesteringsselskab = 0042,
    ATPBidrag = 0046,
    OPBidrag = 0047,
    SkattefriRejseOgBefordringsgodtgoerelse = 0048,
    VeardiAfFriHelaarsbolig = 0050,
    VeardiAfFriSommerbolig = 0051,
    VeardiAfFriLystbaad = 0052,
    VeardiAfFriMedieRadioLicens = 0053,
    VeardiAfAndrePersonaleGoderOverBagatelgraense = 0055,
    VeardiAfAndrePersonaleGoderUdenBagatelgraense = 0056,
    AIndkomstFraAldersOpsparing = 0057,
    ASkatAfAldersOpsparing = 0058,
    JubilaeumsgratialeOgFratraelsesgodtgoerelse = 0069,
    JubilaeumsgratialeOgFratraelsesgodtgoerelseIndbetaltTilPension = 0070,
    JubilaeumsgratialeOgFratraelsesgodtgoerelseTingsgaver = 0071,
    BidragTilObligatoriskUdenlandsSocialSikring = 0089,
    GruppelivIPensionsindskud = 0091,
    SundhedsforsikringIPensionsindskud = 0096,
    TilbageBetalingAfKontanthjaelp = 0098,
    AIndkomstUdbetaltSomFeriepenge = 0113,
    LoenmodtagersPensionsandel = 0147,
    ArbejdsgiversPensionsandel = 0148,
    IndbetalingPaaIkkeGroenlandskPensionsordning = 0157,
    SkatAfIndbetalingPaaIkkeGroenlandskPensionsordning = 0158,
    BruttoferiepengeForTimeloennede = 0198,
    Bruttoferiepenge = 0201,
    NettoferiepengeTimeloennede = 0202,
    ButtoferiepengeFortsatFunktionaer = 0210,
    OpsparingTilSoegneOgHelligdagsBetaling = 0248,
    OpsparingTilFeriefridage = 0249,
}
